# SPDX-License-Identifier: LicenseRef-CSSL-1.0

channelmod = {
  max_chan = 1;
  modellist = "cfo_models";
  cfo_models = (
    {
      model_name = "rfsimu_channel_enB0";
      type = "AWGN";
      ploss_dB = 0;
      noise_power_dB = -50;
      forgetfact = 1;
      offset = 0;
      ds_tdl = 0;
      cfo_hz = 10000;
    }
  );
};
