# SPDX-License-Identifier: LicenseRef-CSSL-1.0

add_executable(lpp_request_capabilities_test lpp_request_capabilities_test.c)
add_dependencies(tests lpp_request_capabilities_test)
add_test(NAME lpp_request_capabilities_test COMMAND lpp_request_capabilities_test)
target_link_libraries(lpp_request_capabilities_test PRIVATE asn1_lpp)

add_executable(lpp_nr_dl_tdoa_provide_assistance_data_test lpp_nr_dl_tdoa_provide_assistance_data_test.c)
add_dependencies(tests lpp_nr_dl_tdoa_provide_assistance_data_test)
add_test(NAME lpp_nr_dl_tdoa_provide_assistance_data_test COMMAND lpp_nr_dl_tdoa_provide_assistance_data_test)
target_link_libraries(lpp_nr_dl_tdoa_provide_assistance_data_test PRIVATE asn1_lpp)
