PRSs =
(
  {
    Active_gNBs = 1;
    prs_config0 = (
    {
      gNB_id = 0;
      PhysCellID            = 0;       
      ARFCN                 = 640008;
      SCS                   = 0;
      # 0=15kHz, 1=30kHz, 2=60kHz, 3=120kHz must match this TRP's real dl_subcarrierSpacing
      NumPRSResources       = 1;
      PRSResourceSetPeriod  = [20, 2];
      SymbolStart           = [8];
      NumPRSSymbols         = [2];
      NumRB                 = 24;
      RBOffset              = 0;
      CombSize              = 2;
      REOffset              = [0];
      PRSResourceOffset     = [0];
      PRSResourceRepetition = 1;
      PRSResourceTimeGap    = 1;
      NPRS_ID               = [0];
      MutingPattern1        = [];
      MutingPattern2        = [];
      MutingBitRepetition   = 1;
    }
    );

#config1 is a copy of config0, added to replicate the terrestrial tests with 2 gnBs
    prs_config1 = (
    {
      gNB_id = 1;
      PhysCellID            = 0;      
      ARFCN                 = 497230;
      SCS                   = 0;
      # 0=15kHz, 1=30kHz, 2=60kHz, 3=120kHz must match this TRP's real dl_subcarrierSpacing
      NumPRSResources       = 1;
      PRSResourceSetPeriod  = [20, 2];
      SymbolStart           = [8];
      NumPRSSymbols         = [2];
      NumRB                 = 24;
      RBOffset              = 0;
      CombSize              = 2;
      REOffset              = [0];
      PRSResourceOffset     = [0];
      PRSResourceRepetition = 1;
      PRSResourceTimeGap    = 1;
      NPRS_ID               = [0];
      MutingPattern1        = [];
      MutingPattern2        = [];
      MutingBitRepetition   = 1;
    }
    );
  }
);
